# Generated by Django 4.0.6 on 2022-07-25 20:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationalid',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(13)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_phone',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(13)]),
        ),
    ]
