# Generated by Django 4.0.6 on 2022-07-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_nationalid_alter_profile_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationalid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_phone',
            field=models.IntegerField(default=0),
        ),
    ]
