# Generated by Django 4.0.6 on 2022-07-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_nationalid_alter_profile_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationalid',
            field=models.CharField(default='xx-xxxxx-xx', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
