# Generated by Django 4.0.6 on 2022-07-28 02:42

import applications.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.IntegerField(default=applications.models.randpermitno, unique=True)),
                ('permit_type', models.CharField(choices=[('Import', 'Import '), ('Export', 'Export')], max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('port_of_entry_exit', models.CharField(choices=[('HarareAirport', 'HarareAirport'), ('BulawayoAirport', 'BulawayoAirport'), ('HarareRailwayStation', 'HarareRailwayStation'), ('BeitBridgeBorderPost', 'BeitBridgeBorderPost'), ('ChirunduBorderPost', 'ChirunduBorderPost'), ('NyamapandaBorderPost', 'NyamapandaBorderPost')], max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('NotApproved', 'NotApproved')], default='waiting', max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('Purpose', models.CharField(choices=[('sale', 'sale'), ('privateuse', 'privateuse'), ('Consumption', 'Consumption'), ('Medicinal', 'Medicinal')], max_length=20)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('date_approved', models.DateTimeField(default=datetime.datetime.today)),
                ('StatusReason', models.CharField(default='waitingstatus', max_length=100)),
                ('Approving_officer', models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Approving_officer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
