# Generated by Django 4.0.6 on 2022-08-03 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_approving_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Expiry_of_permit_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
