# Generated by Django 4.0.6 on 2022-08-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_expiry_of_permit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='permit_paid',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
