# Generated by Django 4.0.6 on 2022-07-25 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100, unique=True)),
                ('farm_address', models.CharField(max_length=100)),
                ('farming_type', models.CharField(choices=[('Subsistence', 'Subsistence '), ('Commercial', 'Commercial')], max_length=20)),
                ('farm_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nationalid', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField()),
                ('fuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
