# Generated by Django 4.0.6 on 2022-07-25 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0002_remove_farmer_nationalid_alter_farmer_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='fuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
