# Generated by Django 4.0.6 on 2022-07-26 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0003_alter_farmer_fuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coi', models.FileField(default='N/A', upload_to='documents')),
                ('cr', models.FileField(default='N/A', upload_to='documents')),
                ('tax_clearence', models.FileField(default='N/A', upload_to='documents')),
                ('fuserd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
