# Generated by Django 4.0.6 on 2022-07-29 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0005_alter_documents_fuserd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='farmer',
            new_name='farm',
        ),
    ]
