# Generated by Django 4.0.6 on 2022-07-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_rename_farmer_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_district',
            field=models.CharField(choices=[('Mutare', 'Mutare'), ('Odzi', 'Odzi'), ('Mazowe', 'Mazowe'), ('Mvurwi', 'Mvurwi'), ('HarareSouth', 'HarareSouth'), ('hwedza', 'hwedza'), ('midlands', 'midlands')], default='xxx', max_length=50),
        ),
    ]
